#!/bin/sh

GSETTINGS_SCHEMA=org.gnome.desktop.interface

if [ $# -gt 1 ]; then
    echo "to many arguments"
    exit 1
elif [ $# -lt 1 ]; then
    case $(gsettings get $GSETTINGS_SCHEMA color-scheme) in
    "'prefer-dark'")
        echo "on"
        ;;
    *)
        echo "off"
        ;;
    esac
    exit 0
fi

on() {
    gsettings set $GSETTINGS_SCHEMA color-scheme 'prefer-dark'
    gsettings set $GSETTINGS_SCHEMA gtk-theme 'adw-gtk3-dark'
}

off() {
    gsettings set $GSETTINGS_SCHEMA color-scheme 'default'
    gsettings set $GSETTINGS_SCHEMA gtk-theme 'adw-gtk3'
}

case $1 in
'on')
    on
    ;;
'off')
    off
    ;;
'toggle')
    case $(gsettings get $GSETTINGS_SCHEMA color-scheme) in
    "'prefer-dark'")
        off
        ;;
    *)
        on
        ;;
    esac
    ;;
*)
    echo "invalid argument '$1' use one of: on, off, toggle"
    exit 1
    ;;
esac

exit 0
